
version: '3.6'
name: "database"
services:
  db:
    image: mysql:8
    ports:
      - ${DBPORT}:${DBPORT}
    expose:
      - ${DBPORT}
    volumes:
      - db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DBPASSWORD}
      MYSQL_DATABASE: ${DBNAME}

volumes:
  db:
    driver: local
