package com.springapitest.restapi.controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import com.springapitest.restapi.models.Card;
import com.springapitest.restapi.repositories.CardRepository;

import com.springapitest.restapi.models.Transaction;
import com.springapitest.restapi.repositories.TransactionRepository;

@Controller // Defines a Controller
@RequestMapping(path = "/") // URL's starts with / (after Application path)

public class MainController {

    // This means to get the bean called xRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    private CardRepository cardRepository;

    @Autowired
    private TransactionRepository transactionRepository;

    @GetMapping(path = "/cards")
    public @ResponseBody Iterable<Card> getAllCards() {
        // This returns a JSON or XML
        return cardRepository.findAll();
    }

    @GetMapping(path = "/transactions")
    public @ResponseBody Iterable<Transaction> getAllTransactions() {
        // This returns a JSON or XML
        return transactionRepository.findAll();
    }
}
