package com.springapitest.restapi.controllers;

import com.springapitest.restapi.utility.StringResponse;
import org.springframework.beans.factory.annotation.Autowired;

import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import com.springapitest.restapi.models.Card;
import com.springapitest.restapi.repositories.CardRepository;

import com.springapitest.restapi.models.Product;
import com.springapitest.restapi.repositories.ProductRepository;


import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

@RestController // Defines a Controller
@RequestMapping(path = "/") // URL's starts with / (after Application path)

public class ProductController {

    // This means to get the bean called xRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    private CardRepository cardRepository;
    @Autowired
    private ProductRepository productRepository;



    @GetMapping(path = "/product/{productId}")
    public Object getProductsByProductId(@PathVariable("productId") Long productId) {
        try {
            return new ResponseEntity<>(productRepository.findByProductId(productId), HttpStatus.OK) ;
        }
        catch(Exception e) {
            System.out.println("Something went wrong.");
            System.out.println( "Error message: "+ e.getMessage());
            return new ResponseEntity<>(new StringResponse("Error: "+ e.getMessage()), HttpStatus.BAD_REQUEST);
        }
    }

    @GetMapping(path ="/createproduct")
    public Object createproduct() {
        try {

            Product productToSave =  new Product();
            productToSave.setProductId(12345678l);
            productToSave.setName("Producto 123");
            productToSave.setDescription(" Esta es la descripción de mi producto 123");

            productRepository.save(productToSave);

            return productToSave;
        }
        catch(Exception e) {
            System.out.println("Something went wrong.");
            System.out.println( "Error message: "+ e.getMessage());
            return new StringResponse("Error: "+ e.getMessage());
        }
    }



}
